version: "3.8"

services:
  server:
    container_name: server
    build: ./server
    ports:
      - "4000:80"
    stdin_open: true

  client1:
    container_name: client1
    build: ./client
    network_mode: host
    environment:
      - PORT=3001
    stdin_open: true

  client2:
    container_name: client2
    build: ./client
    network_mode: host
    environment:
      - PORT=3002
    stdin_open: true

  client3:
    container_name: client3
    build: ./client
    network_mode: host
    environment:
      - PORT=3003
    stdin_open: true
